# Generated by Django 3.0.8 on 2020-07-13 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_auto_20200712_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='modifyDate',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='modifyDate',
            new_name='modify_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modifyDate',
            new_name='modify_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
